# Generated by Django 5.2.6 on 2026-08-28 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewCoinSetupApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('trade_type', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED_WIN', 'Closed (Win)'), ('CLOSED_LOSS', 'Closed (Loss)'), ('CLOSED_BREAKEVEN', 'Closed (Breakeven)'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('position_size_usd', models.FloatField(default=1000.0)),
                ('leverage', models.IntegerField(default=1)),
                ('pnl_usd', models.FloatField(default=0.0)),
                ('pnl_pct', models.FloatField(default=0.0)),
                ('r_multiple', models.FloatField(default=0.0)),
                ('pattern_tag', models.CharField(blank=True, choices=[('Pump → Dump → Accumulate', 'Pump → Dump → Accumulate (Classic Retail Trap)'), ('Instant Dump → Range → Slow Recovery', 'Instant Dump → Range → Slow Recovery (VC Dump)'), ('Slow Bleed Downwards', 'Slow Bleed Downwards (Low Demand, High FDV)'), ('Pump → Hold High → Expand', 'Pump → Hold High → Expand (Institutional Support)'), ('Fake Pump → Sharp Dump → Dead Range', 'Fake Pump → Sharp Dump (Rug Risk)'), ('Sideways First → Breakout Later', 'Sideways First → Breakout Later (Stealth Accumulation)'), ('Pump → Fake Dump → V-Shaped Recovery', 'Pump → Fake Dump → V-Recovery (Liquidity Trap)'), ('Announcement Arb Pump → Quick Fade', 'Announcement Arb Pump → Quick Fade (Bot Frenzy)'), ('Futures-Led Cascade', 'Futures-Led Cascade (Perp Dominance)'), ('Exploit/Backlash Dump → Rebound', 'Exploit Dump → Rebound (Narrative Fix)'), ('Delisting Shadow', 'Delisting Shadow (Pre-delist Bleed)'), ('Narrative Rotation Surge', 'Narrative Rotation Surge (Chain Hop)')], max_length=100, null=True)),
                ('psychology_state', models.CharField(choices=[('DISCIPLINED', '🎯 Disciplined Execution'), ('FOMO_ENTRY', '🔥 FOMO / Chasing Pump'), ('REVENGE_TRADE', '😡 Revenge Trade after Loss'), ('EARLY_EXIT', '😰 Early Exit / Fear of Loss'), ('GREED_OVERLEVERAGED', '🤑 Greed / Over-leveraged'), ('PANIC_CUT', '😱 Panic Cut at Lows')], default='DISCIPLINED', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('chart_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.FloatField(default=10000.0)),
                ('risk_per_trade_pct', models.FloatField(default=2.0)),
                ('trading_tier', models.CharField(choices=[('FREE', 'Free Starter'), ('PRO', 'Pro Trader'), ('INSTITUTIONAL', 'Institutional Edge')], default='PRO', max_length=20)),
                ('avatar_symbol', models.CharField(default='⚡', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
